### ISSUE TITLE
SwiftCLI from Xcode terminal

### ISSUE THREAD

**Issue by raptorxcz** [jakeheis/SwiftCLI#101]
Hello,

I made Swift script which runs some shell commands (mostly Fastlane). For running shell I use class `Task`.  

I am using rbenv for changing Ruby version. Everything works when I compile script and executing it in terminal. 
When I execute my script directly from Xcode it fails. Somehow Xcodes terminal does not know nothing about rbenv. 

I find out the issue is related with terminals type and environment. https://mgrebenets.github.io/xcode/2019/04/04/xcode-build-phases-and-environment

Any idea how to fix my issue?

Thank you

**Comment by jakeheis** [comment]
I'm afraid this issue lies outside of this project -- if I'm understanding you correctly, the problem isn't with `Task` but with the Xcode terminal environment which I am not familiar with. If I've misunderstood and the problem does lie with the `Task` class, please feel free to reopen!
