### ISSUE TITLE
Mandatory key arguments

### ISSUE THREAD

**Issue by acecilia** [jakeheis/SwiftCLI#107]
Hi 👋 

From the readme seems like `@Key` can only be optional:

> The variable wrapped by @Key can be any type conforming to ConvertibleFromString as described above. It must be optional, or the Swift compiler will crash.

Would it be possible to support mandatory `@Key` arguments? Like:

```swift
@Key("-n", "--number-of-times", description: "Say the greeting a certain number of times")
var numberOfTimes: Int
```

```shell
greeter greet --number-of-times 4
```

They would work as a `@Param`, but having the flag prefixing them, so:
* The arguments do not need to be passed in any specific order
* The flag text slightly explains the argument being passed, making it more readable

One example were mandatory keys are available is [thor](https://github.com/rails/thor), the command line library for ruby. In [here](http://whatisthor.com/) it says:

> You can also specify that a particular option is required.

**Comment by jakeheis** [comment]
Hi @acecilia, sorry for the delay in response. https://github.com/jakeheis/SwiftCLI#option-groups should accomplish what you're looking for here -- using something like `.exactlyOne($numberOfTimes)` will make that key mandatory. I'm gonna go ahead and close this issue but feel free to reopen if option groups don't fix your usecase
