### ISSUE TITLE
Update README in swift-3.0-beta5 branch

### ISSUE THREAD

**Issue by rbukovansky** [jakeheis/SwiftCLI#17]
Hi,
could you please update README.md in swift-3.0-beta5 branch how to use SwiftCLI for Swift 3.0? I'm trying to build my swift 3.0 app, but with standard package configuration I'm getting tons of error during `swift build` for SwiftCLI package.

Thank you.

**Comment by jakeheis** [comment]
Thanks for the suggestion, done in 274f14abafe760df7a0d1b515f0733a60ec9cbac. Changing the dependency in `Package.swift` to look like this should be enough:

`.Package(url: "https://github.com/jakeheis/SwiftCLI", Version(1, 3, 0, prereleaseIdentifiers: ["beta"]))
`
