### ISSUE TITLE
Compile errors [Swift 3.0]

### ISSUE THREAD

**Issue by rbukovansky** [jakeheis/SwiftCLI#18]
Hi,
thanks for #17 but I'm still getting errors. See attached build log.
Could you please take a look?

Thanks a lot.
[build.log.txt](https://github.com/jakeheis/SwiftCLI/files/421873/build.log.txt)

**Comment by jakeheis** [comment]
Are you using the latest Swift beta version? The errors you are getting look like they would come from a pre-beta6 compiler

**Comment by rbukovansky** [comment]
I do have Swift 3.0 Beta 5 on my Ubuntu VM, but I can't compile Swift from source code (low RAM). That Beta 6 compiler is necessary?

**Comment by rbukovansky** [comment]
OK. I made fresh install of Ubuntu, Swift 3.0 PREVIEW 6 and I'm still getting errors. Could you please take a look? Thanks.
[build.log.txt](https://github.com/jakeheis/SwiftCLI/files/424331/build.log.txt)

**Comment by rbukovansky** [comment]
Well, see #19. :)
