### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by rbukovansky** [jakeheis/SwiftCLI#23]
I'm trying to figure it out, but I have failed...
I would like to have global options for my application, i.e. -v/--verbose for verbose response and -h/--help for help of specified command (-v and -h without command can default to version and help).
Am I able do it using SwiftCLI?

Thanks for help.

**Comment by rbukovansky** [comment]
:sos: :cry:

**Comment by rbukovansky** [comment]
@jakeheis Are you able to answer this for me, please? Thanks.

**Comment by jakeheis** [comment]
This is not a built-in feature of `SwiftCLI`. The same functionality should be able to be achieved by implementing a general `VerboseCommand` implementation of `OptionCommand` and then subclassing `VerboseCommand` to create your specialized commands.

Having said that, pull requests to generalize global command options would be welcome
