### ISSUE TITLE
Color encoding the help menu using Rainbow

### ISSUE THREAD

**Issue by kdawgwilk** [jakeheis/SwiftCLI#32]
It would be great if support was added to output the help menu in colors when the terminal supports it.  This can be done using [Rainbow](https://github.com/onevcat/Rainbow)

**Comment by jakeheis** [comment]
From my experience, most terminal applications don't color the output in the help menu. As such, I'm not sure it makes sense to include this functionality in `SwiftCLI`. It would however be extremely for one to do in their own project by implementing custom message generators and Rainbow, so I would encourage you to do that:
```swift
public protocol UsageStatementGenerator {
    func generateUsageStatement(for command: Command, optionRegistry: OptionRegistry?) -> String
}

public protocol MisusedOptionsMessageGenerator {
    func generateMisusedOptionsStatement(for command: Command, incorrectOptionUsage: IncorrectOptionUsage) -> String?
}
```
