### ISSUE TITLE
How do we listen for a ctrl-C to stop any async processes we might have triggered

### ISSUE THREAD

**Issue by kdawgwilk** [jakeheis/SwiftCLI#33]
I am wanting to get notified if a ctrl-C or other key combination was sent while the CLI tool is running so I can react accordingly.

**Comment by jakeheis** [comment]
`SwifCLI` doesn't have any specific built in functionality for this, but using C's `signal` function should work:
```swift
signal(SIGINT) { (val) in
     // React
}
```
