### ISSUE TITLE
[FeatReq] Subcommands

### ISSUE THREAD

**Issue by rbukovansky** [jakeheis/SwiftCLI#36]
@jakeheis For my project I will need to have what we can call `subcommands` or `application areas`. Most of the time user will need, due to complexity of application, to specify "area" he wants to work within and then command for that area. Similar to `git remote` command. Let me better explain in CLI commands:

```
Code area:
$ cx code add readme.md
$ cx code commit "Init commit"
$ cx code status

Issues area:
$ cx issue add "Something is broken" <-- different add to add in Code area
$ cx issue show 1234
$ cx issue resolve 1234

Build area:
$ cx build run
$ cx build restart

etc.
```
Do you think it would be possible to add it to SwiftCLI? Thank you.

**Comment by rbukovansky** [comment]
BTW If you are looking for inspiration how to expand SwiftCLI further, take a look on this Golang CLI library: https://github.com/urfave/cli

**Comment by jakeheis** [comment]
I'm afraid I don't have time to implement a feature of this size right now but I'd certainly be open to a pull request after discussing a high level implementation plan

**Comment by rbukovansky** [comment]
That's OK, it was just an idea resulting from needs of my project. So far I can replace that with commands styled like this: `cx code-add`

**Comment by jakeheis** [comment]
Done in `4.0.1`

**Comment by rbukovansky** [comment]
Wow! Shiny! 😉 

You did awesome job, sir! Thank you! 👏
