### ISSUE TITLE
[FeatReq] Bash completion

### ISSUE THREAD

**Issue by rbukovansky** [jakeheis/SwiftCLI#37]
Would be possible also add bash completion to SwiftCLI? For inspiration take a look on https://github.com/urfave/cli as well... :)

Thank you.

**Comment by jakeheis** [comment]
I'm not sure the benefit gained from this feature would justify it's implementation complexity, but if a high level plan for how this could be implemented was laid out I would better be able to judge whether I thought it was worth building out the feature

**Comment by jakeheis** [comment]
Zsh completion done in `4.0.1`, holding off on Bash completion for now

**Comment by jakeheis** [comment]
Closing for now, will reopen if there is demand for Bash completion later on
