### ISSUE TITLE
Update Swift 4 branch

### ISSUE THREAD

**Issue by jacobbudin** [jakeheis/SwiftCLI#41]
Should the [`swift_4` branch](https://github.com/jakeheis/SwiftCLI/tree/swift_4) be updated with the changes from `master`? I would like to make a Swift 4-related pull request to fix deprecation warnings such as:

> warning: 'characters' is deprecated: Please use String or Substring directly

I assume I should make the pull request to this branch. If I'm wrong, let me know. Thanks.

**Comment by jakeheis** [comment]
The `swift_4` branch is no longer in use as it's been merged into master. If there are any changes that are necessary for new versions of Swift (as there may be with 4.0.2) then a pull request can be opened directly against master!

I'll delete that branch now to clear up the confusion.
