### ISSUE TITLE
Cannot be used with Cocoapods

### ISSUE THREAD

**Issue by victor** [jakeheis/SwiftCLI#5]
This issue is not really an issue with SwiftCLI, but with the current developer tools state. But I wanted to document it anyway for future users of the library.

I was trying to create the Cocoapods' podspec so that I could link to the library as a 3rd party framework. After 2 days hitting into a wall, I realized that it is not currently possible to link to dynamic libraries (or frameworks) from command line apps, because they are single file apps and lack the necessary bundle structure.

There is a [cumbersome mechanism](http://colemancda.github.io/programming/2015/02/12/embedded-swift-frameworks-osx-command-line-tools/) for using a bundle that runs inside a command line tool and provides the 3rd party frameworks, but it is too complex to be used with Cocoapods anyway.

I have opened a radar ([rdar://20250458](http://openradar.appspot.com/20250458)) about this issue.

So, for now, even though Cocoapods supports Swift frameworks, the recommended way to install the library is to copy it the source files. (Of course, if you were not building a command line app, there would be no problem. But then, what do you need a command line parser for?)

**Comment by jakeheis** [comment]
Closing now that SPM is supported a650b806e44cf5382e9267685b632f299be47c4f
