### ISSUE TITLE
add support for --version in built-in version command. 

### ISSUE THREAD

**Issue by dastrobu** [jakeheis/SwiftCLI#54]
I like the built-in [version-command](https://github.com/jakeheis/SwiftCLI#version-command
). Consider to add support for the pretty standard `--version` flag. 

I do prefer to use this flag quite often if I want to check for a version of a command, where I can't remember the exact syntax to use. Since the short flag `-v` sometimes refers to "verbose", I try to avoid using `-v`.

**Comment by jakeheis** [comment]
`4.3.0`
