### ISSUE TITLE
Question: CLIs without "command"

### ISSUE THREAD

**Issue by dastrobu** [jakeheis/SwiftCLI#55]
Is there support for CLIs without a specific command? If so, some hints to that in the README would be helpful. 

In detail, if I want to develop a simple command line tool, which takes some flags and some files as input, e.g. 
```
foo -a bar.txt baz.log -f
```
I do not have a command. Instead I have just some flags `-a` and `-f`, plus and arbitrary number of optional collected parameters. 
I good real world example of such a tool is the famous `rm` from the GNU core utils, which, unlike the macOS version of `rm` accepts flags at any position.

**Comment by dastrobu** [comment]
Thanks for the explanation, I would have preferred an interface, though, that supports easy uses cases as default (no commands) and more complex ones (many different commands and routing routing) by adding more code. I guess the community would adopt SwiftCLI for more projects if the API is kept simpler for simple things. Anyway, thanks for the quick reply.

**Comment by jakeheis** [comment]
You're welcome to make a pull request with any concrete improvements! My goal isn't to make a project the whole community will adopt, SwiftCLI is just a project that I've used in my own projects which I (rightfully) believed others would find useful as well. It's definitely built for full featured command line apps -- you don't need really any features in this lib if you're only including one command. I suggest looking around at other tools to see what fits your use case rather than lamenting the fact that one lib doesn't fit your use case quite right!

**Comment by dastrobu** [comment]
Don't get me wrong, I do like the project and I think it is quite helpful, even in cases where only flags, key value options and arguments are needed. I did already check other projects, on CLI interfaces in Swift and I think SwiftCLI is a very promising one. So I just wanted to make a constructive comment.

**Comment by jakeheis** [comment]
I'm glad you find SwiftCLI promising! But I fear in your comment you may have made the common mistake of equating open source maintainers with maintainers of proprietary projects -- I'm certainly happy whenever someone finds my project useful enough to use in their own projects, but it is not my job to add features to entice the community into using my project over other projects. There are a lot of great projects out there, and I'd encourage you to check out such projects as https://github.com/nsomar/Swiftline which may be a better fit for you than this project.

On the other hand, if you wish to help contribute to SwiftCLI, I'd encourage you to make a proposal of a feature you'd like to see! Off the top of my head, maybe you'd like to see something like this:

```swift
protocol SingleCommand: Command {}

extension SingleCommand {
    
    func run() -> Int32 {
        let cli = CLI(name: name)
        cli.parser = Parser(router: SingleCommandRouter(command: self))
        return cli.go()
    }
    
}
```

in SwiftCLI, which would allow use like:

```swift
class RmCommand: SingleCommand {
   let name = "rm"
   func execute() throws {}
}

RmCommand.run()
```

or perhaps you have something totally different in mind. In any case, when it comes to requesting features from projects which are offered to you for free, it's much more constructive to offer a concrete suggestion than passingly say its not simple enough for you or the community.

**Comment by dastrobu** [comment]
Thanks for the long explanation. I did not request implementing any feature and I am happy to hear that you are open for pull requests and improvements - which not everyone is.
