### ISSUE TITLE
Version doesn't work if using SingleCommandRouter

### ISSUE THREAD

**Issue by yonaskolb** [jakeheis/SwiftCLI#59]
`version` `--version` or `-v` don't work if using a `SingleCommandRouter`

**Comment by jakeheis** [comment]
This is actually be design -- the idea is that by using that router, you will literally only be using a single command, not the version command, not the help command, and no other commands of your own. A big reason for this is that your single command may use -v and -h for other things (e.g. a verbose flag).

**Comment by jakeheis** [comment]
This is hopefully now clarified by the new section in the README at https://github.com/jakeheis/SwiftCLI#single-command-clis
