### ISSUE TITLE
LlamaKit is defunct now

### ISSUE THREAD

**Issue by danthorpe** [jakeheis/SwiftCLI#6]
It has been merged with Rob Rix's https://github.com/antitypical/Result µframework. As a community, we're trying to consolidate on this as the Result type.

**Comment by jakeheis** [comment]
With the new error handling model in Swift 2, a Result type is no longer necessary in this project. It has been removed in the [swift2](https://github.com/jakeheis/SwiftCLI/tree/swift2) branch which will be merged in once Xcode 7 comes out of beta
