### ISSUE TITLE
Usage description is incorrect for SingleCommand

### ISSUE THREAD

**Issue by yonaskolb** [jakeheis/SwiftCLI#60]
If using a `SingleCommandRouter` the help usage contains the command name.
```
Usage: tool commandName <parameter> [options]
```

Even if the command.name is set to "" there are 2 spaces
```
Usage: tool  <parameter> [options]
```

**Comment by jakeheis** [comment]
Fixed by 26ea292446de0ba3ec5df013e3d539007ffecb4c, and some of the confusion on CLI name vs command name should hopefully be clarified by the new section at https://github.com/jakeheis/SwiftCLI#single-command-clis
