### ISSUE TITLE
Parameter descriptions

### ISSUE THREAD

**Issue by yonaskolb** [jakeheis/SwiftCLI#61]
It might be nice to be able to give a `Parameter` a description so it can be show in the usage output for the command. Perhaps this can be under a `Parameters` list similar to how `Options` is shown.
You could argue if the parameter is required the usage info could go into the command description, but at the moment the usage for a command doesn't show it's own description, it only does in the command list

**Comment by jakeheis** [comment]
Is this issue sufficiently solved by long descriptions in usage statements (56d73e8bf288f5686abb9b397728f6e99901368e)?

**Comment by yonaskolb** [comment]
Yep!
