### ISSUE TITLE
Help command argument

### ISSUE THREAD

**Issue by yonaskolb** [jakeheis/SwiftCLI#64]
It would be great if the inbuilt help command accepted a command argument to get help on subcommands, as an alternative to `--help`

```sh
tool command --help # currently works
tool help command # new way
tool help command subcommand # could even walk the command tree
```

I can look at this when I have some free time

**Comment by jakeheis** [comment]
Definitely agree this should be built in -- should be done in 72627c4d456119bef48d9291af8a8bdc4402ca0d, please confirm that this does all you think it should!

**Comment by yonaskolb** [comment]
Looks great! I guess some tests will verify all those case. Thanks!
