### ISSUE TITLE
Question: Idiomatic way to restrict values of parameter to enum and surface that to user

### ISSUE THREAD

**Issue by bjo0** [jakeheis/SwiftCLI#73]
I'm looking for the idiomatic way to restrict values of parameter to enum and surface that to user. Apologies if this is not the right way to surface this question.

For example, if there are only 3 supported values for a required parameter, what's the best way to surface that info to the user? If there is no idiomatic way, can we treat this as a feature request?

**Comment by jakeheis** [comment]
Right now I think the best way to go about something like this would be as such:

```swift
class RunCmd: Command {
    
    enum Speed: String {
        case slow
        case fast
    }
    
    let name = "run"
    let shortDescription = "Runs something"
    let longDescription = """
    Runs something. <speed> must be one of:
      - slow
      - fast
    """
    
    let speed = Parameter()
    
    func execute() throws {
        guard let speed = Speed(rawValue: speed.value) else {
            throw CLI.Error(message: "Speed must be either 'slow' or 'fast'")
        }
        
        print("Running: \(speed.rawValue)")
    }
    
}
```

which allows for use as such:

```shell
> runner run --help

Usage: runner run <speed> [options]

Runs something. <speed> must be one of:
  - slow
  - fast

Options:
  -h, --help      Show help information

> runner run medium
Speed must be either 'slow' or 'fast'
> runner run fast
Running: fast
```

This of course is all manually done, and `SwiftCLI` doesn't automatically do anything to restrict parameter values.

Do you have any ideas what this would ideally look like?

**Comment by barrymjones** [comment]
I haven't really considered how it would be implemented or integrated into the project, but the rough idea is...

My initial thought is a class/protocol similar to `Option` called `Choice`, that receives a set of permissible values (not necessarily as an enum) and calculates the longDescription, guard statement, and error throwing automatically similar to how you did it.

**Comment by jakeheis** [comment]
Check out https://github.com/jakeheis/SwiftCLI#parameters-with-non-string-values, specifically the section on enums. This should provide most of the functionality you're looking for, all that's left to do would be construct the `longDescription` but that shouldn't be too difficult when using `CaseIterable`.  Feel free to reopen if other issues arise!
