### ISSUE TITLE
"too many arguments (4468) -- limit is 4096" error

### ISSUE THREAD

**Issue by Dschee** [jakeheis/SwiftCLI#74]
I'm just rebasing my tool [BartyCrouch](https://github.com/Flinesoft/BartyCrouch) to use SwiftCLI but after making the switch on first try on one of our larger projects, I came across this error:
```
2018-12-13 17:34:49.112 bartycrouch[12963:3427202] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'too many arguments (4468) -- limit is 4096'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff35bb6e65 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff61c12720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff35bb6c97 +[NSException raise:format:] + 201
	3   Foundation                          0x00007fff37eabaf3 -[NSConcreteTask launchWithDictionary:error:] + 774
	4   bartycrouch                         0x000000010371373a $S8SwiftCLI4TaskC6launch030_19E0ACB72F1C972020BFBD69850F9J1FLLyyF + 506
	5   bartycrouch                         0x0000000103713249 $S8SwiftCLI4TaskC7runSyncs5Int32VyF + 25
	6   bartycrouch                         0x0000000103716626 $S8SwiftCLI3run_9arguments9directoryySS_SaySSGSSSgtKFTf4xnn_n + 390
	7   bartycrouch                         0x0000000103712669 $SAbort trap: 6
```

Looks like there's an arguments limit to tasks executed in the command line. Can this be fixed within this library (easiliy) or do I need to build a wrapper around the `run(:arguments:)` method and run my command multiple times until it has worked through all arguments?

The usage code is probably [this line](https://github.com/Flinesoft/BartyCrouch/blob/work/big-refactoring/Sources/BartyCrouchKit/OldCommandLine/CodeCommander.swift#L28) in case you're wondering.

**Comment by Dschee** [comment]
Oh, I just tried to implement running my command multiple times until I recognized that I need to pass all arguments at once in order for the tool to work properly (a `Localizable.strings` file is generated and it needs to contain all localizations, so a workaround would be more complicated since I also need to merge multiple Localizable.strings file outputs to one). So a solution to this max arguments problem would be nice.

By the way, here's my own implementation of the `run` command which worked fine:
https://github.com/Flinesoft/BartyCrouch/blob/stable/Sources/BartyCrouchKit/CommandLine/Commander.swift#L13

**Comment by jakeheis** [comment]
Hmm, `SwiftCLI.Task` is build on `Process` and essentially does exactly what your project appears to being doing right now in terms of arguments -- compare https://github.com/jakeheis/SwiftCLI/blob/master/Sources/SwiftCLI/Task.swift#L198 and  https://github.com/Flinesoft/BartyCrouch/blob/stable/Sources/BartyCrouchKit/CommandLine/Commander.swift#L14. Is this an issue that doesn't arise with the current implementation?

**Comment by Dschee** [comment]
It does, I‘ve found that out after writing this. Any idea for a fix? Or do I need to work around this?

**Comment by Dschee** [comment]
I see, thank you for the info. I'll need to work around this then.
