### ISSUE TITLE
Questions: Idiomatic way to specify default command

### ISSUE THREAD

**Issue by raleighr3** [jakeheis/SwiftCLI#77]
Is there a way to specify a command to run if one is not given on the cmd line?
Right now I am hijacking Command.arguments to do this.
Something like this: 

```swift
let args = CommandLine.arguments
let cli = MyCli()
if args.count > 1 {
    cli.run(Array(args.dropFirst()))
} else {
    cli.run(["default"])
}
```
run then calls
```swift
cli.go(with: args)
```

Is there a better way?

**Comment by jakeheis** [comment]
This is now possible in `5.3.0`:

```swift
cli.parser.routeBehavior = .searchWithFallback(DefaultCommand())
```

Feel free to reopen if this doesn't fix your issue!

**Comment by MPLew-is** [comment]
Is this possible on a `CommandGroup` level? For instance, being able to call `mycli group command` and `mycli group`, and have them route to the same underlying `Command`?

**Comment by jakeheis** [comment]
This is not possible right now, but I think it would be make sense to add that functionality. Feel free to open a new issue requesting this feature. No promises about when I'll get around to implementing it, but I do think it should be added eventually!
