### ISSUE TITLE
Idiomatic way to invoke a command from another command

### ISSUE THREAD

**Issue by edulpn** [jakeheis/SwiftCLI#86]
I did a quick search on previous issues and I think what I want to accomplish might not be a good idea (since nobody apparently thought about this before), but is there a way to chain command invocations (extra: passing arguments) with SwiftCLI?

What I ideally would like to accomplish is something like this:
```
class Command1: Command {
    func execute() throws {
        ...
        var command2 = Command2()
        command2.param = "param" //this gives a 'param' is get-only error
        try command2.execute()
    }
    ...
}

class Command2: Command {
    @Param var param: String?

    func execute() throws {
        ...
    }
    ...
}
```

**Comment by jakeheis** [comment]
There's no built-in way to do this -- I think generally the pattern at this point would be to call a common function from both commands:

```swift
class Command1: Command {
    func execute() throws {
        doSomething(with: "otherValue")
    }
    ...
}

class Command2: Command {
    @Param var param: String?

    func execute() throws {
        doSomething(with: param)
    }
    ...
}

func doSomething(with this: String) {
     ...
}
```

I've been hesitant to add a feature which makes invoking different commands easier, as `Command` is more about adding structure to the list of arguments passed by the user. If you just want to invoke common functionality from two commands, I think it makes more sense to factor that functionality out of any individual command.

**Comment by jakeheis** [comment]
Closing -- feel free to reopen if you think this should be in `SwiftCLI` / have an idea of what it could look like!
