### ISSUE TITLE
Consider: Supporting @env: syntax for reading options.

### ISSUE THREAD

**Issue by orj** [jakeheis/SwiftCLI#91]
A common idiom in command line apps is to support reading arguments from the environment. This is particularly useful in CI/CD situations where often config items or secrets are passed via environment variables.  Eg:

```
mycommand action --apiKey @env:API_KEY
```

This style of passing arguments can also help when the content of the env key might cause command parsing issues (eg multiline values).

**Comment by jakeheis** [comment]
I'm hesitant to build this in by default given that (as far as I know) it's not a super common way to pass arguments, and it's fairly easy to implement if this is functionality you need: 

```swift
struct EnvironmentStoredValue: ConvertibleFromString {
    
    let value: String
    
    init?(input: String) {
        if input.hasPrefix("@env:") {
            self.value = ProcessInfo.processInfo.environment[...]
        } else {
            self.value = input
        }
    }
}

...

@Key("--api-key") var value: EnvironmentStoredValue?
```

I'll close for now, but if this pattern is more common than I realize and you believe it should be baked into this library, feel free to reopen!
